services:
  tinablog-linux-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinablog-linux-dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"  # 应用端口
      - "2222:22"    # SSH端口
    environment:
      - TZ=Asia/Shanghai
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=tinablog
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - tinablog-network
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tinablog
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tinablog-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  tinablog-network:
    driver: bridge 