#决定是否以守护进程的方式运行Nginx，默认值为ON。如果设置为off，则Nginx将以前台进程的方式运行，便于调试。
daemon off;
# 决定是否启用Nginx的进程池机制，默认值为ON。如果设置为off，则Nginx将不会创建进程池，而是直接运行主进程，会导致并发处理能力大大下降。
master_process off;

#user  nobody;
worker_processes auto; #设置worker进程的数量为1，如果设置为auto，则根据CPU核心数自动设置

# 启用详细日志记录，方便调试
# error_log logs/error.log debug; # 设置为debug级别，显示最详细的信息
error_log stderr debug; # 错误日志直接输出到终端，方便测试运行时查看错误日志，设置日志级别为 notice 。

# pid  logs/nginx.pid;

# events 配置块
events {
    worker_connections  1024; # 设置每个worker进程的最大连接数为1024
}


http {
    include       mime.types;
    default_type  application/octet-stream; # 默认的MIME类型

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    # 记录所有HTTP请求到access.log
    access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;
    
    # 博客模块全局数据库配置
    blog_db_connection "host=127.0.0.1;user=root;password=3344207732;database=blog;port=33060";
    blog_db_auto_connect on;

    server {
        listen       80; # 监听的端口号
        server_name  localhost; # 服务器名称

        #charset koi8-r;

        # 启用主机级别的访问日志
        access_log  logs/host.access.log  main;

        # Vue项目的静态文件目录
        root  html/blog/dist;
        
        # 对根路径的请求处理
        location / {
           index  index.html index.htm;
           blog_path html/blog/dist;
           try_files $uri $uri/ /index.html; # 支持Vue的history路由模式
        }

        # 对/blog/路径的请求处理
        location /api/ {    
            blog_enable_cache on;
            blog_cache_time 60;
        }
        
#         location /api/auth/ {
#             proxy_pass http://localhost:你的端口/api/auth/;
#         }
        
        # 其他静态资源配置
        location /static/ {
            alias /path/to/static/files/;
         }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html; # 设置错误返回页面
        # 设置错误返回页面的位置
        location = /50x.html { 
            root   html;
        }
    }
}
